TeamAudio/reaspeech

app/templates/reascript.lua
reascripts/ReaSpeech/source/Fonts.lua
reascripts/ReaSpeech/source/ReaSpeechAPI.lua

Requests were failing when trying to use a huggingface-hosted instance of ReaSpeech that was auto-negotiating a HTTP2 session which our response parsing wasn't ready for (matching the main response header - we're looking for something formatted like "HTTP/x.x nnn" but apparently HTTP/2 confidently says "let there be no indicated decimal in the version").
Since we're in curl-in-reaper-land, this change just asks curl to force a HTTP/1.1 session instead. Modified are 1) the loader, 2) the font fetcher and 3) the `ReaSpeechAPI` processing calls.

Add "--http1.1" to curl requests

---

app/run.py
app/templates/nav.html
app/webservice.py

introduce a new `run.py` argument: `--enable-swagger-ui`.
when supplied, `webservice.py` sets the FastAPI `docs_url` to `/docs` and the link shows up on the ReaSpeech install instructions and `/docs` is active. 
when not supplied, the link is not rendered and direct access of `/docs` now returns a 404.

#63 - optional swagger UI

---

app/worker.py

this ended up being a pretty simple task - the job id is available via `self.request`

Use celery job id instead of original filename for output filename

---

reascripts/ReaSpeech/source/Theme.lua
reascripts/common/libs/ImGuiTheme.lua
reascripts/common/tests/TestImGuiTheme.lua

ImGui.Col_TabActive was renamed to ImGui.Col_TabSelected in the 0.9.2 upgrade to ReaImGui. We aren't using ReaImGui's shims, which might have worked around this issue, but nonetheless we shouldn't fail when a color/style function doesn't exist. This change includes nil-handling for ImGuiTheme so that missing colors/styles do not contribute to the color/style counts that are popped.

Handle missing theme colors/styles, add TabSelected

---

Dockerfile
Dockerfile.gpu
docker-compose.gpu.yml
docker-compose.yml
docs/development.md

Some modifications to make development on Linux easier:
- Improve error handling and stick to uid:gid for all user settings in Dockerfiles
- Update documentation and clean up docker-compose*.yml files
In order to run Docker Compose on Linux, it's nearly always going to be necessary to add SERVICE_UID and SERVICE_GID args to docker-compose.yml so that they match up with the current user. I looked into ways to automate this, but it seems like Docker does not make this very easy. See ingyhere's comments and linked articles on https://stackoverflow.com/questions/56844746/how-to-set-uid-and-gid-in-docker-compose

Docker Compose Linux fixes

---

reascripts/ReaSpeech/source/Transcript.lua
reascripts/ReaSpeech/source/TranscriptUI.lua
reascripts/ReaSpeech/tests/TestTranscript.lua

The return values for ImGui.TableGetColumnSortSpecs changed in https://github.com/cfillion/reaimgui/commit/316e66e35fba56664fbeca83a7d5ccd78dc20b8b which is why column sorting stopped working. Resetting to the default order was also broken, possibly due to a change in behavior of the "specs_dirty" result.
Also fixed is sorting columns with table values, which fixes behavior for the hidden "tokens" column.

Fix sorting for transcript table

---

reascripts/ReaSpeech/.luacheckrc
reascripts/ReaSpeech/source/CurlRequest.lua
reascripts/ReaSpeech/source/ReaSpeechAPI.lua
reascripts/ReaSpeech/source/ReaSpeechWorker.lua
reascripts/common/.luacheckrc
reascripts/common/libs/TableUtils.lua
reascripts/common/tests/TestTableUtils.lua

after a few false starts, i've finally got a functional `CurlRequest` that hides a lot of the messy stuff involved with that backend interaction paradigm. `ReaSpeechAPI` is now mostly just wrappers around `CurlRequest` functions. sync+async calls are supported - the latter is instantiated via the `async` factory that pops a few extra bits of state around whatever other options would be passed into the request (stuff like the output and sentinel files).
basic interface (see `CurlRequest:init()` for available options):
- (sync, successfull call) `CurlRequest.new(options):execute()` -> `<server response>`
- (sync, failed call) `CurlRequest.new(options):execute()` -> `nil`, fail/timeout errors specified in options are called as applicable
- (async) `CurlRequest.async(options):execute()` -> …

Extract a CurlRequest class

---

reascripts/ReaSpeech/source/ReaSpeechWorker.lua

Capitalize job status so that it looks more professional and less shouty. Rename "Uploading" to "Sending Media" since this may be a local transfer.

Format job status in progress bar

---

reascripts/ReaSpeech/source/CurlRequest.lua
reascripts/ReaSpeech/source/Logging.lua
reascripts/ReaSpeech/source/ReaSpeechControlsUI.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ReaSpeechWidgets.lua
reascripts/ReaSpeech/source/ReaSpeechWorker.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/ReaSpeech/tests/TestLogging.lua
reascripts/ReaSpeech/tests/TestReaSpeechUI.lua

as discussed in https://github.com/TeamAudio/reaspeech/pull/78#discussion_r1742688265, this adds generic logging capability that can be applied to any of our Lua modules via a call like `Logging.init(self_reference_to_target_object, "Prefix")`.
i aimed to reflect current behavior, but there is one big deviation that comes to mind. the time in the log message will now reflect when the message was generated, not when it's displayed in the console.
modules that referenced `app:log` or `app:debug` have been updated with the new generic logging.

Generic Logging

---

reascripts/ReaSpeech/source/ReaSpeechActionsUI.lua
reascripts/ReaSpeech/source/ReaSpeechWorker.lua
reascripts/ReaSpeech/source/include/globals.lua

One reason for the flickery screen updates during processing is that errors when checking job status were uncaught, causing intermittent lack of rendering of the actions and transcript portions of the UI. An example of such an error is "[CurlRequest, LOG] Unable to open progress file". Another cause was an error when attempting to format a nil job status. This change improves error handling. There still is a bit of flicker as the progress bar gets reused for various purposes, but it's less jumpy now that large portions of the UI remain visible.
This also adds an improved dump function which has nicer output in my eyes, and eliminates extra trailing commas.

Fix job status checks

---

reascripts/ReaSpeech/source/CurlRequest.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua

The `--write-out %output{filename}` feature only works with curl 8.3.0 or newer. ReaSpeech currently gets stuck with older versions of curl because the lack of this feature means the sentinel file never gets written. This affects Linux Mint, which comes with curl 7.81.0.
Detect the curl version and conditionally support the sentinel file if curl is new enough. Otherwise, fall back on checking for the existence of the progress file (curl's stderr destination). This means that an async curl process may be considered "ready" even though it is still executing, so the error handling is not as robust in that case.

Support older versions of curl with respect to sentinel files

---

reascripts/common/libs/Storage.lua
reascripts/common/libs/mock_reaper.lua
reascripts/common/tests/TestStorage.lua

This change adds a reusable common library for persisting configuration data to ExtState or ProjExtState. It is a rewrite of an internal class we called OptionsConfig, with a design partially inspired by the "Atom" concept (here called a "Cell") from the React community.
Features:
- Supports ExtState (persistent or not) and ProjExtState, and can be extended with additional storage engines
- Automatic type conversion (strings, booleans, and numbers) and built-in default handling to make usage less error-prone
- Enables writing derived cells that can perform additional computation on reads and/or writes
The initial intended purpose of this library is to facilitate adding persistence to ReaSpeech settings.

Add storage library

---

reascripts/ReaSpeech/Makefile
reascripts/ReaSpeech/source/ASRControls.lua
reascripts/ReaSpeech/source/ReaSpeechWidgets.lua
reascripts/ReaSpeech/tests/TestReaSpeechUI.lua
reascripts/common/libs/Storage.lua
reascripts/common/tests/TestStorage.lua

Use the new Storage library to make ASR controls persistent across launches of the application.
Added a Storage.memory helper for creating memory-based cells.

Add persistence for ASR controls

---

reascripts/ReaSpeech/source/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua

For some reason we don't understand yet, using ToolWindow for ReaSpeechUI causes AlertPopups to fail to display in case of ASR errors (like when the model name is invalid). Popups from the Export modal are not affected. This revert fixes the main build while we look into the issue.

Revert ToolWindow application to ReaSpeechUI

---

reascripts/ReaSpeech/source/TranscriptAnnotationsUI.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/common/libs/mock_reaper.lua

A few changes to the transcript annotations UI:
- Use a tab bar instead of a combo box for the annotation type
- Default to project markers
- Default to segment granularity
- Ensure that popup windows stay on top

Use tab bar for annotations, tweak defaults

---

reascripts/ReaSpeech/libs/ToolWindow.lua
reascripts/ReaSpeech/source/AlertPopup.lua
reascripts/ReaSpeech/source/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ReaSpeechWelcomeUI.lua
reascripts/ReaSpeech/source/TranscriptUI.lua
reascripts/ReaSpeech/tests/TestToolWindow.lua

The `present`/`presenting` is now baked in by default. Using `present` instead of `open` provides some safety when trying to open a window when you might not be safely within a `render` call.
This was a problem that manifested as the `AlertPopup` not popping up when a transcription error occurred. Internally, its `show` method was calling `open`. Roughly what was happening was that it was trying to attach a popup without any active `Begin`/`End` parent window context to attach to (plz forgive this bad and possibly incomplete/incorrect interpretation and articulation).

ToolWindow fixes

---

reascripts/ReaSpeech/libs/ToolWindow.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/ReaSpeech/source/Tween.lua
reascripts/ReaSpeech/tests/TestToolWindow.lua
reascripts/ReaSpeech/tests/TestTween.lua
reascripts/common/libs/ImGuiTheme.lua
reascripts/common/libs/mock_reaper.lua
reascripts/common/tests/TestImGuiTheme.lua

Extends the `ImGuiTheme` module to accept functions as style arguments. The `Tween` module is a bit hairy but towards the goal of interacting shallowly with intermediate objects. Define a new tween via `Tween(f, time_provider)`, instantiate it with a start/end/duration and optional callback then just call the result of that as often as you can/want. It's documented in the module header.
Initially I've left in some logging calls that I'll remove before merging. The one integration point implemented is in `TranscriptExporter:open()`. I've temporarily left it a bit explicit to describe the arguments and provide a conversational starting point to figure out where to go with the API - again, before merging back to main.
Fading in the `TranscriptExporter` over 0.2 seconds on `open()`: …

Tweening module for that smoothe taste 

---

poetry.lock
pyproject.toml

Upgrade to the latest version of faster-whisper. No change in functionality is expected. Tested on Win/Mac/Linux.

Upgrade to faster-whisper 1.0.3

---

reascripts/ReaSpeech/source/ASRActions.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua
reascripts/ReaSpeech/source/Transcript.lua
reascripts/ReaSpeech/source/TranscriptImporter.lua
reascripts/ReaSpeech/source/TranscriptSegment.lua
reascripts/ReaSpeech/source/TranscriptWord.lua
reascripts/ReaSpeech/tests/TestReaSpeechUI.lua
reascripts/ReaSpeech/tests/TestTranscript.lua
reascripts/common/libs/ReaUtil.lua
reascripts/common/tests/TestReaUtil.lua

Adds the ability to import a JSON transcript previously exported by ReaSpeech.
This adds a button ("Import Transcript") next to the "Process..." buttons in the main interface. The popup has a simple file selector, and when "Import" is clicked ReaSpeech will attempt to load the JSON content from the file and and re-attach whichever media items/takes were associated with each segment found.
I'm thinking of this as a stepping stone to some kind of autosave system. Like...maybe a dropdown somewhere allowing a quick revert to the last [configurable x] invocations (clicks on a "process" button). 🤔🤔🤔🤔
Opening the popup and importing some JSON:
https://github.com/user-attachments/assets/b23044aa-6828-470f-abdb-13adbcfefa31

Transcript Importer

---

reascripts/ReaSpeech/Makefile
reascripts/ReaSpeech/libs/ToolWindow.lua
reascripts/ReaSpeech/source/ASRControls.lua
reascripts/ReaSpeech/source/ColumnLayout.lua
reascripts/ReaSpeech/source/ReaSpeechActionsUI.lua
reascripts/ReaSpeech/source/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ReaSpeechWelcomeUI.lua
reascripts/ReaSpeech/source/ReaSpeechWidgets.lua
reascripts/ReaSpeech/source/ReaSpeechWorker.lua
reascripts/ReaSpeech/source/SampleMultipleUploadControls.lua
reascripts/ReaSpeech/source/SettingsControls.lua
reascripts/ReaSpeech/source/TranscriptAnnotationsUI.lua
reascripts/ReaSpeech/source/TranscriptEditor.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/ReaSpeech/source/TranscriptSegment.lua
reascripts/ReaSpeech/source/TranscriptUI.lua
reascripts/ReaSpeech/source/Widgets.lua
reascripts/ReaSpeech/tests/TestCSVWriter.lua
reascripts/ReaSpeech/tests/TestReaSpeechUI.lua
reascripts/ReaSpeech/tests/TestSRTWriter.lua
reascripts/ReaSpeech/tests/TestToolWindow.lua
reascripts/ReaSpeech/tests/TestTranscript.lua
reascripts/ReaSpeech/tests/TestTranscriptAnnotations.lua
reascripts/common/libs/Trap.lua

Introduce a `Trap` callable object to use instead of `app:trap`. This offers a few advantages:
- Simplifies runtime dependencies, since libraries do not need to depend on an `app` global
- Reduces the amount of overhead due to indirection and closure creation

Introduce a Trap library in place of app:trap

---

app/faster_whisper/core.py

With the faster-whisper upgrade, tqdm is getting called automatically to update progress state. This was previously not the case, so we were doing it ourselves. Now, progress is getting double-logged, and sometimes (presumably due to the VAD filter) it is causing the progress bar to jump back and forth.

Remove tqdm calls for faster-whisper

---

reascripts/ReaSpeech/libs/ToolWindow.lua
reascripts/ReaSpeech/source/ASRActions.lua
reascripts/ReaSpeech/source/TranscriptAnnotationsUI.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/ReaSpeech/source/TranscriptImporter.lua
reascripts/ReaSpeech/tests/TestToolWindow.lua
scripts/reawatch
scripts/reawatch-gpu
scripts/reawatch-gpu.bat
scripts/reawatch.bat

Fixes #120
The always-on-top feature of ImGui seems problematic on Linux, as it steals focus from other applications and renders them unusable. Instead, we should just focus the popup window if it is not focused already. This would solve the same problem I had intended to solve with always-on-top: when a window is already open, but buried by the main window, it's very difficult to discover what happened to it, and the button just seems broken.
I was unable to get `SetNextWindowFocus` to bring the popup window to the top. It does appear to set focus, but it remains buried. So, I instead opted for closing the window and using the `presenting` flag to cause it to be reopened on the next render.

Focus popup windows instead of using always-on-top

---

reascripts/ReaSpeech/Makefile
reascripts/ReaSpeech/libs/ToolWindow.lua
reascripts/ReaSpeech/source/ASRActions.lua
reascripts/ReaSpeech/source/Fonts.lua
reascripts/ReaSpeech/source/KeyMap.lua
reascripts/ReaSpeech/source/ReaSpeechActionsUI.lua
reascripts/ReaSpeech/source/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ReaSpeechWidgets.lua
reascripts/ReaSpeech/source/TranscriptAnnotationsUI.lua
reascripts/common/libs/Ctx.lua

I'm still seeing intermittent issues with invalid contexts on OSX (bug #122). It typically happens before the first deferred call to `ReaSpeechMain:loop()`. I tried making this initial call immediate instead of deferred, but it made the problem worse.
As a workaround, I think we have to assume that the context could be invalidated at any point, and ensure that it gets recreated before each iteration of the render loop. This means that we can't store the context as an instance variable, since it can be replaced, and we don't want to hold onto the old context. We could store a factory instead, if we wanted to reduce dependency on the `ctx` global; for the sake of simplicity, I have opted to return to using the global here.

Rebuild ImGui Context when invalid

---

reascripts/ReaSpeech/source/AlertPopup.lua
reascripts/ReaSpeech/source/ReaSpeechWidgets.lua
reascripts/ReaSpeech/source/Theme.lua
reascripts/ReaSpeech/source/TranscriptExporter.lua
reascripts/ReaSpeech/source/Widgets.lua
reascripts/common/libs/PathUtil.lua
reascripts/common/tests/TestPathUtil.lua

This adds a checkbox and conditionally some target filename-related text under the file selector & "Choose file" button in `TranscriptExporter`.
If no full path is provided, it'll be relative to the active REAPER project's resource path.
On success, the alert popup now shows the filename-portion of the exported path. That filename is a "reveal" link which will attempt to open & focus the file in a platform-dependent way before closing the popup.
This is a work-in-progress whose full scope might be more than just this PR. Mainly just trying to start addressing general UX around this feature.
Closes #104.
quick demo:
https://github.com/user-attachments/assets/0e2ba0d2-75cd-40a3-b24d-8f94388e22aa

UX improvements for TranscriptExporter filename

---

.dockerignore
.gitignore
Dockerfile
Dockerfile.gpu
app/run.py
app/worker.py
docs/no-docker.md
poetry.lock
pyproject.toml

This change removes the Redis dependency in favor of SQLite, which does not require running a service. This simplifies running ReaSpeech outside of Docker. It's still possible to use Redis by passing parameters into run.py. Fixes #95

Use SQLite instead of Redis

---

reascripts/ReaSpeech/source/ui/SettingsControls.lua

Fix wiring of logging state now that `Logging` must be written as `Logging()`

Fix persistence for logging options

---

reascripts/ReaSpeech/source/ui/TranscriptEditor.lua

In the edit window, if you click on an input (like the word's text input) and then press the right arrow key, it navigates to the next word, and overwrites the contents of that word. This change disables the custom keyboard handling when an input is in use.

Ignore keyboard events on edit window when an input is active

---

app/run.py
docker-compose.gpu.yml
docker-compose.yml
reascripts/ReaSpeech/Makefile

When using run.py from the command line, it is inconvenient to need two Lua versions (we support Lua 5.3 for REAPER 6 users). In addition, the linter/tests may not be necessary if a user just wants to run ReaSpeech from the git repository without using Docker. This change adjusts the Makefile to enable publishing for specific Lua versions, adjusts run.py to publish for Lua 5.4 by default, and re-enables all tests and Lua versions in Docker Compose environments.
Hopefully this will not mess up the release process. @mikeylove please let me know if anything stands out.

Only depend on Lua 5.4 for default run.py target

---

reascripts/ReaSpeech/source/libs/CurlRequest.lua

The changes in PR #140 cause the application to fail to start on Windows and Linux. This appears to be due to the exit code returned by reaper.ExecProcess when running a background process (timeout < 0). On Windows, the exit code is 259, and on Linux, it's -1004. At least on Windows, my understanding is that this code indicates that the process is still running. If a process is running in the background, there's not really a sensible exit code to report immediately.
There's still some improvement to be made in the error message reported when the service goes down ("Couldn't open output file"), but this change at least fixes startup on Windows on Linux.

Fix startup failures due to curl error handling change

---

reascripts/ReaSpeech/source/libs/CurlRequest.lua

The regex the curl error check during the sentinel check in `CurlRequest` wasn't catching this on Windows. I don't have a good grasp on why except that it a quick look at the debug output made this seem suddenly obvious. Hey, sometimes that's the way it goes. 🤷🏻‍♂️

Loosen curl error check regex 

---

app/run.py

Available via `--port` argument or `ENV[PORT]`

Add a "port" argument to run.py

---

app/whisper_cpp/core.py

The default `chunk_size` used by pywhispercpp to download models is very small, resulting in slow downloads, especially on Windows. By calling `download_model` directly, we can tune this value.

Speed up model downloads when using whisper.cpp

---

Dockerfile.gpu

This change updates Dockerfile.gpu to build pywhispercpp with CUDA support. This requires building whisper.cpp with the CUDA development toolkit, which is quite large (about 6GB). To avoid increasing the size of the reaspeech-gpu image, Dockerfile.gpu has been reorganized as a multi-stage build, using the "devel" CUDA image to build, and the "runtime" image as the basis for the final image. Fixes #148
In order to get CUDA support to work, it was necessary to use a more recent version of whisper.cpp than the one the latest version of pywhispercpp targets. This was done by using a git checkout and updating the whisper.cpp submodule to a specific version tag. Due to a breaking change (a renamed whisper.cpp setting, "suppress_non_speech_tokens" became "suppress_nst"), a minor …

Enable GPU acceleration for whisper.cpp in Docker

---

reascripts/ReaSpeech/source/ui/ASRActions.lua
reascripts/ReaSpeech/source/ui/TranscriptImporter.lua
reascripts/ReaSpeech/source/ui/TranscriptUI.lua

this applies "quick import" behavior (skipping the importer dialog if file selections are made) consistently between the "Import Transcript" button under Speech Recognition and the "+" tab's "Load Transcript" menu option. 
while i was in there i went ahead and made it handle multiple files similarly to drag/drop loading.
if there are problems with the files selected for loading, an alert will inform the user per-file what the error was. files without loading problems are loaded, and there's no explicit "success" message or indication beyond new transcript tabs showing up.
https://github.com/user-attachments/assets/b990a12b-45c9-4349-a006-af1055735e88

Apply "quick import" to "+" tab and allow multiple file selection

---

reascripts/ReaSpeech/source/libs/Plugin.lua
reascripts/ReaSpeech/source/main/Transcript.lua
reascripts/ReaSpeech/source/ui/ReaSpeechControlsUI.lua
reascripts/ReaSpeech/source/ui/ReaSpeechPlugins.lua
reascripts/ReaSpeech/source/ui/TranscriptUI.lua
reascripts/ReaSpeech/source/ui/widgets/TabBar.lua

Plugins can now implement `drop_zones(file_list)`:
- implementations should return a list of candidate drop zones based on the provided `file_list` argument
- structure is `{ render: <drop zone rendering function>, on_drop: <actual drop handler> }`
`TranscriptUI` now offers a loader (that can load multiple files) and (if more than one file is dragged in) a combiner that will create a merged transcript from all dragged-in files.
https://github.com/user-attachments/assets/543fa69d-ccde-4319-8865-ca76dff68cc1

Plugin-defined Top-level Drop Zones

---

reascripts/ReaSpeech/source/main/TranscriptSegment.lua
reascripts/ReaSpeech/source/ui/ASRPlugin.lua
reascripts/ReaSpeech/source/ui/TranscriptUI.lua

currently, if you ask ReaSpeech to process a collection of tracks/items that sees the same source file more than once, only one of those media item/take references will be retained and added as a transcript segment.
this change retains those extra references, and for each one will add the found segments for a given source file to the transcript. yes, this means that you can have the same text show up multiple times in a transcript. no, i don't think that's weird, it's _your_ weird project, friend!
this also changes the start/end columns in the transcript table to reflect the segment's start/end relative to the full project timeline.
from here i'm picturing what the ux might look like for resolving overlap conflicts. 🤔
https://github.com/user-attachments/assets/d4ea3d1d-fbd5-4a25-9bee-4405b …

Retain extra project references when processing a source file

---

README.md
docs/no-docker.md

This change adds instructions for running ReaSpeech via the command line on OSX, using the whisper.cpp engine, which allows users to get GPU acceleration on Apple Silicon-based Macs. To get GPU support on Mac, one has to run ReaSpeech outside of Docker, which requires a basic development environment (python3.10, luac4.5, make, etc.) to build and run the application.

Apple Silicon GPU instructions

---

app/util/audio.py
app/worker.py

In an attempt to figure out why .m4a files were resulting in empty transcripts, I tried running ffmpeg via the command line, and it had no problem converting it to a .wav file with the audio intact. My understanding is that the main reason .m4a files are different is that their metadata gets stored at the end of the file. Since our `load_audio` function was piping audio into ffmpeg, I think this was defeating ffmpeg's file format detection; it had no file extension since it was reading from stdin, and it could not determine the file type by looking at the beginning of the stream.
I tried passing the filename instead of a file stream into the ffmpeg library, and sure enough, .m4a files are detected and handled properly. Since we use temp files to pass the audio from the web service to the …

Make ffmpeg operate directly on temp file

---

reascripts/ReaSpeech/source/ui/Icons.lua
reascripts/ReaSpeech/source/ui/ReaSpeechControlsUI.lua
reascripts/ReaSpeech/source/ui/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ui/SettingsControls.lua

The Settings tab feels like it's always in the way. This is one possible way to hide it when not in use. This change adds a gear icon button that can show or hide the Settings tab, and enables the close button on the Settings tab. Open to suggestions about layout/placement.

Add Settings gear button and enable show/hide of Settings tab

---

reascripts/ReaSpeech/source/libs/Logging.lua
reascripts/ReaSpeech/source/main/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ui/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ui/SettingsControls.lua

With the Settings plugin no longer initialized at app startup, the saved logging (log/debug) preferences weren't getting loaded. This ~swaps~ moves the `Storage` initialization for `Logging` over to ~that module~ `ReaSpeechMain` and has `SettingsControls` reference ~those relocated storage cells~ `Logging`'s `show_logs/show_debug_logs` in its checkbox widgets.

Move logging Storage initialization to Logging module

---

reascripts/ReaSpeech/source/libs/ToolWindow.lua
reascripts/ReaSpeech/source/main/ReaSpeechMain.lua
reascripts/ReaSpeech/source/ui/ASRControls.lua
reascripts/ReaSpeech/source/ui/AlertPopup.lua
reascripts/ReaSpeech/source/ui/ColumnLayout.lua
reascripts/ReaSpeech/source/ui/KeyMap.lua
reascripts/ReaSpeech/source/ui/ReaSpeechControlsUI.lua
reascripts/ReaSpeech/source/ui/ReaSpeechUI.lua
reascripts/ReaSpeech/source/ui/ReaSpeechWelcomeUI.lua
reascripts/ReaSpeech/source/ui/ReaSpeechWidgets.lua
reascripts/ReaSpeech/source/ui/SampleMultipleUploadControls.lua
reascripts/ReaSpeech/source/ui/SettingsControls.lua
reascripts/ReaSpeech/source/ui/TranscriptAnnotationsUI.lua
reascripts/ReaSpeech/source/ui/TranscriptEditor.lua
reascripts/ReaSpeech/source/ui/TranscriptExporter.lua
reascripts/ReaSpeech/source/ui/TranscriptImporter.lua
reascripts/ReaSpeech/source/ui/TranscriptUI.lua
reascripts/ReaSpeech/source/ui/Widgets.lua
reascripts/ReaSpeech/source/ui/widgets/Button.lua
reascripts/ReaSpeech/source/ui/widgets/ButtonBar.lua
reascripts/ReaSpeech/source/ui/widgets/Checkbox.lua
reascripts/ReaSpeech/source/ui/widgets/Combo.lua
reascripts/ReaSpeech/source/ui/widgets/FileSelector.lua
reascripts/ReaSpeech/source/ui/widgets/ListBox.lua
reascripts/ReaSpeech/source/ui/widgets/NumberInput.lua
reascripts/ReaSpeech/source/ui/widgets/TabBar.lua
reascripts/ReaSpeech/source/ui/widgets/TextInput.lua
reascripts/ReaSpeech/tests/TestWidgets.lua
reascripts/ReaSpeech/tests/libs/TestToolWindow.lua
reascripts/ReaSpeech/tests/mock_reaper.lua

I'm seeing lots of "expected a valid ImGui_Context" errors on Mac, not just at startup but during transcription. They crash the app. We previously made a change to introduce a `Ctx()` helper that automatically recreates the ImGui context whenever it becomes invalid, but we did not use it throughout the codebase because of performance concerns. However, given the current behavior, I think it's best to use this helper everywhere, even if it introduces some slowdown, because the alternative means crashes and data loss.
I think one possible reason this is happening during transcription is that we are making blocking curl calls to check for transcription status, and this increases the likelihood that the ImGui context will be garbage collected due to delays between frame rendering. I'm not …

Call Ctx everywhere

---

.github/workflows/docker-publish.yml

Change the test for the Docker Hub link in the release notes to make it look more better and more clearer.

change dockerhub link text in release notes

---

reascripts/ReaSpeech/source/ui/ReaSpeechControlsUI.lua
reascripts/ReaSpeech/source/ui/Widgets.lua

BeginChild returns a boolean, and if that value is false, it means that the child is entirely clipped. In that case, we can't call EndChild or it will throw an assertion error and crash the application. This can be repro'd by making the window very small.

Only call EndChild if BeginChild succeeds

---

reascripts/ReaSpeech/source/ui/TranscriptEditor.lua

The PushButtonRepeat/PopButtonRepeat functions were removed from ImGui. They enabled holding the mouse button down to quickly navigate through words. There's a way to get this functionality by handling various mouse events, but I'm not sure how important it is to keep that behavior. This fixes the edit window so that it displays again.

Fix edit window due to ReaImGui 0.10 upgrade
